### PR TITLE
Porting to Redmine 5

### PR DESCRIPTION
**Pull request by quynh1-nguyenthinhu**
Hello @y-matsuda-maedadev, @fuminori-ido-m,
I updated the source code to compatible with Redmine 5.
The changes are as follows:
* Add gem matrix
* Replace render :text by render :plain
* Permit parameter
* Update folder structure, module name to math with file name according to Zeitwerk rule

### CODE REVIEW

**Comment by quynh1-nguyenthinhu** [comment]
Hello @ichylinux ,
Could you please help me to check this PR for porting redmine_backlogs to Redmine 5?

**Comment by ichylinux** [comment]
hi, we are now examining whether this PR is also compatible with Redmine 4.x.x.
so please wait for a while.

thank you

**Comment by fuminori-ido-m** [comment]
Hello @quynh1-nguyenthinhu , Thank you for your contribution!

I have some questions on your PR 

1. Where is the newly added gem `matrix` used?  I could not find out any referencing to matrix(or vector) in this redmine_backlogs plugin.
2. Your modified context_menu calling [here](https://github.com/maedadev/redmine_backlogs/pull/15/commits/a7dd4573ced9479ad1e8969f18fab02a97746c14#diff-c8d124d4de73993bf3d1fbc8bdd5fe0307e5d4859a4c669c4001044d76dfc3e4) resulted
   <details>
    <summary>like this (just render 'true' string)</summary>

    clipboard-202307211002-1gae9
   </details>

    - This means just `context_menu` is not working on this page in our environment.  The line was added in 2013 [here](https://github.com/backlogs/redmine_backlogs/commit/68c1ad46f3dc26e3750c59b98ee4454736cde3d3) so that  it looks something is missed (any setup?) in our environment...
3. I wonder what your commit-comment `porting to redmine5` means, because Your PR is working with remine 4.2 (except for context_menu).

**Comment by quynh1-nguyenthinhu** [comment]
Hello @ichylinux. Thank you for your response.

I would like to answer your questions:
1. When install redmine_backlogs in Redmine 5 (with command rake redmine:backlogs:install), I got the following error:
> LoadError: cannot load such file -- matrix

After adding gem matrix, plugin can be installed successfully

2. I'm sorry, this is my mistake. 
With [this code](https://github.com/backlogs/redmine_backlogs/commit/68c1ad46f3dc26e3750c59b98ee4454736cde3d3), '500 Internal error' will occur when user access a Release detail page (On Redmine 4 & Redmine 5).
Therefore, we decided to fix it. However, the previous fix action is incorrect.
I've just added a new commit to fix that issue.
With this new update, the issue context menu will be displayed when user right-click to an issue in Release detail page.

3. My PR is compatible with both Redmine 4 and Redmine 5. So, I mean: support Redmine 5 compatibility. Sorry for the confusion.

**Comment by fuminori-ido-m** [comment]
Hi @quynh1-nguyenthinhu , thank you for your update!

I confirmed that context menu is fixed and now working!

Still I wonder about `matrix` gem because it looks for me that redmine + backlogs work without the `gem 'matrix'` line in Gemfile (unlike the other gems like `prawn`).  Could you please show us what error did you see when trying to run redmine+backlogs without `matrix` gem?

**Comment by quynh1-nguyenthinhu** [comment]
Hi @ichylinux, @fuminori-ido-m  ,

In Redmine 5.0.3, without `matrix` gem, I got following error when executing `rake redmine:backlogs:install`:

> rake aborted!
> LoadError: cannot load such file -- matrix
> /usr/local/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
> /usr/local/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
> /usr/local/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
> /usr/local/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
> /usr/local/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn/transformation_stack.rb:10:in `<top (required)>'
> /usr/local/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn.rb:67:in `require_relative'
> /usr/local/lib/ruby/gems/3.1.0/gems/prawn-2.4.0/lib/prawn.rb:67:in `<top (required)>'
> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:60:in `require'
> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:55:in `each'
> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:55:in `block in require'
> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:44:in `each'
> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler/runtime.rb:44:in `require'
> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/lib/bundler.rb:187:in `require'
> /opt/redmine-5.0.3/config/application.rb:18:in `<top (required)>'
> <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
> /opt/redmine-5.0.3/Rakefile:5:in `<top (required)>'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
> /usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> /usr/local/bin/rake:25:in `load'
> /usr/local/bin/rake:25:in `<main>'

**Comment by fuminori-ido-m** [comment]
Thank you for your error report.  I understand that:

- `backlogs` plugin depends on `prawn` gem and it uses `matrix` module.
- `matrix` module is default at ruby 2.x  so that there is no problem on ruby 2.x + redmine + `backlogs` v1.4.4.
- `matrix` module is excluded to gem at ruby 3.x.  That is the reason why ruby 3.x + redmine + `backlogs` v1.4.4 fail.  `backlogs` is now required to declare `matrix` gem explicitly.
- `gem 'matrix'` in Gemfile works with ruby 2.x also because the gem for ruby2.x is downloaded in such a case (our case).

**Pull request merged**
